---
title: "Design Library"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Design Library}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Our design library characterizes designs informally and in code using the MIDA framework, described in [The Idea](/page/idea/).

---

## Designs

--------------------------- -----------------------------------------------------------------------------------------------------------------------
Goal                        Strategy      Design                                                                  Download
--------------------------- ------------- ----------------------------------------------------------------------- --------------------------------
Causal inference            Experimental  [Two-Arm Experiment](/page/two_arm/)                                    <a class="btn btn-default" href="/files/two_arm.R"><i class="fa fa-code" title = "Download code for design"></i></a> <a class="btn btn-default" href="/files/two_arm_template.RDS"><i class="fa fa-clipboard" title = "Download template for design"></i></a>

Causal inference            Experimental  [Two-Way Factorial Experiment](/page/two_way_factorial/)                <a class="btn btn-default" href="/files/two_way_factorial.R"><i class="fa fa-code" title = "Download code for design"></i></a> <a class="btn btn-default" href="/files/two_way_factorial_template.RDS"><i class="fa fa-clipboard" title = "Download template for design"></i></a>

Causal inference            Observational [Regression Discontinuity](/page/regression_discontinuity/)             <a class="btn btn-default" href="/files/regression_discontinuity.R"><i class="fa fa-code" title = "Download code for design"></i></a> <a class="btn btn-default" href="/files/regression_discontinuity_template.RDS"><i class="fa fa-clipboard" title = "Download template for design"></i></a>
--------------------------------------------------------------------------------------------------------------------------------------------------


## Using the design library

There are two main ways you can learn about the designs in the library:

  1. Read through the vignettes (click the links under "Design" in the table above).
  2. If you have [installed DeclareDesign](/), download the code for the design or the design template and create your own, modified versions of the designs. Diagnose them on your own computer using `diagnose_design()` (click on the buttons under "Download" in the table above).
<!--  3. Import designs from the library into the [Design Inspector <i class="fa fa-area-chart" title = "Go to the design inspector" fa-2x></i>](http://shiny.declaredesign.org/inspector/) and investigate their properties. You can also download the code for the designs, modify it, and upload the design back into the inspector again. -->

## Contribute

We encourage you to contribute your research design declaration to the library so that it can be used by other scholars. [Contact us](mailto:contribute@declaredesign.org) for instructions.
