language: r
pandoc_version: 2.7.3
dist: xenial

cache:
  packages: true
  directories:
    - "$HOME/bin"
    - "$HOME/cache"
    
r_packages:
  - blogdown
  - checkpoint
  - devtools
  - diffobj
  - formatR
  - testthat
  - texreg
  - broom
  - pkgdown

env:
  global:
    # CONTENT_FOLDERS are the folders that we want to be cleared out and recreated every time the build runs. Put a folder
    # here if your script depends on the existence of an empty folder at build-time.
    # TOPLEVEL_FOLDERS are the folders that live at the toplevel of the website. For example, you can get to the folder
    # `about` by going to `declaredesign.org/about`. This makes the `about` folder a toplevel folder.
    # CONTENT_FOLDER is the folder where you want all the markdown files to live.
    # PUBLISH_FOLDER is the folder where you want the rendered HTML files to be placed.
    - BASE_URL='https://declaredesign.org'
    - CONTENT_FOLDERS='content/r content/stata public/ content/library public/library/designs'
    - TOPLEVEL_FOLDERS='categories conduct mida r  about library stata'
    - CONTENT_FOLDER='content'
    - PUBLISH_FOLDER='public'
    - BLOG_FOLDER='blog'
    - AWS_ACCESS_KEY_ID='AKIAID5245DAZ3JQXVZQ'
    - secure: KOnPCpOOcZVRog3i2oiEYX/MDEgO+kuvfowaqdkAEfj4nkngPMdlLQqG5A/LDANaYPWILmg/MMxcrA7fWQqKmWV3jRBY0UKkOIuEqEGKjjLAfUHUkl8ugk5GEu1QpnuTpgj2Ful6WbDVReUKxa8BXEsdVlImKMv2Gdhy8rEmpMToAmbrY2IFwUVodCJ8J+YroTh5u/xh7epENcyXnBjVLcHPP5xp94jaJXDyTKofinSRA6AiE2HLYaOZpwKnzTqq9nxWoJlb2m2gtZKIaeDBauop0zTXFVLxIVuYH2S+umEJIG0MtPp4euHgDiduuA+NnF3LKbpLGWU1NxH1GmmPbwqGk/brdL0F2rNmB7r8Vjytsv72f4IFmGQm8uBxXVQMD81YWm2IQWd47vRK0cQgx+QN0J0E+hSE3dzDCax1wxUMUXearjdZI1DBNLEgPf9zjlFz871ljRvTk7+LZotet+7eU3EvEFC8CuG2dnM9Q/cey1HfusDJQ+sbT9796hhloCYJLXtMPL9ibTjz3y3Li1YXRd9b4q1AlNFh68hxXPdSUAFVUePYB8+gANGezTabQBNK7+Oj0zx0s1ydjiiyFHYjdVi96zK17V0fvYYQmXVN+/Ccw4MT6x+q/Lqw7WzRt7bgc37pQT+Gpg/wpguVawrY/AmroKiIstUHCxid8KM=
    - secure: ztLAZpVtU6u+0DgkYlc9Fihe3IAVan+BAgoN57P8QdQszqCRUu406V5/tPBlRxVfS4oPljgLJgWAiZYySnRWSIcuuYEmEKWKgT13DlMgHw9UfJd1oh6/J4lERH4BqmpJcAJNpyH31chbvLzI2dydbl4QTH2BbqubuQEpebbvjJPztJss05dOinOVNiQFXV6RFM60DlVnIsvigfWn9AwNN7eoLWinSWGFBPDZBw6ZGxnYdn/lIgWMtLIbeZ1ks0vdRXAowwmGu2y9XaUycrVTqlr0vb9uf9GOMN0M2Clfs3UMx0aaWXgiqKM/mQ8AVQt6b07jtCNoFUPVq2zOsx1gj2/9+NMa5/rzr7YnrbkTU6SkYyPXWz6Q/gtVdDnb+aIWG7qRTw9ozDS7AKqPKBJsWbIsNxQkjZl0MC3hxWW+gNxHCCCAUGZec8QpiCXRnElEWwkoILqwLsWydp8XiZYkiRJ4xoNRaqPpRsh8HwCamg5l2qEfCAdsr/qwMRFoJB26ADIf/q+/vdcKdqakPXv2yx7z24zK/cn3MnKp//g9SjqjBO+XEpOW2LVqbD4oiA11qUB1bMy58NMetcciq7CbS5jL0SyjfC3jpYPUqb3tJ4KrhIPT0Rmg0lOnEraSzj42xQVKJh5DvTuOl9Si9CFK4EVyVYTrHPJUIIQDypfk7RM=
  matrix:
    # - PACKAGE='DesignLibrary'
    #   GITHUB_OWNER='DeclareDesign'
    #   BRANCH='master'
    #   HOME_FOLDER='library'
    #   PKGDOWN_TEMPLATES='DesignLibrary_pkgdown_templates'
    #   CUSTOM_SCRIPT='design_library.sh'
    # # This empty package entry will build all non-package files on the website
    # # (e.g., the blog posts, the about page, the code of conduct...)
    # - PACKAGE=''
    #   GITHUB_OWNER=''
    #   BRANCH=''
    #   HOME_FOLDER=''
    #   PKGDOWN_TEMPLATES=''
    #   CUSTOM_SCRIPT=''
    # - PACKAGE='randomizr'
    #   GITHUB_OWNER='DeclareDesign'
    #   BRANCH='master'
    #   HOME_FOLDER='r/randomizr'
    #   PKGDOWN_TEMPLATES='pkgdown_templates'
    #   CUSTOM_SCRIPT=''
    # - PACKAGE='strandomizr'
    #   GITHUB_OWNER='DeclareDesign'
    #   BRANCH='web'
    #   HOME_FOLDER='stata/randomizr'
    #   PKGDOWN_TEMPLATES='pkgdown_templates'
    #   CUSTOM_SCRIPT=''
    - PACKAGE='fabricatr'
      GITHUB_OWNER='DeclareDesign'
      BRANCH='master'
      HOME_FOLDER='r/fabricatr'
      PKGDOWN_TEMPLATES='pkgdown_templates'
      CUSTOM_SCRIPT=''
    - PACKAGE='estimatr'
      GITHUB_OWNER='DeclareDesign'
      BRANCH='master'
      HOME_FOLDER='r/estimatr'
      PKGDOWN_TEMPLATES='pkgdown_templates'
      CUSTOM_SCRIPT=''
    - PACKAGE='DeclareDesign'
      GITHUB_OWNER='DeclareDesign'
      BRANCH='master'
      HOME_FOLDER='r/declaredesign'
      PKGDOWN_TEMPLATES='pkgdown_templates'
      CUSTOM_SCRIPT=''

script:
  - ./scripts/install_common_dependencies.sh && ./scripts/run_build_travis.sh

