baseurl = "https://declaredesign.org/"
languageCode = "en-us"
title = "DeclareDesign"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-126973870-1"
disqusShortname = "declaredesign"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
uglyurls = true
paginate = 5 # Default number of blog posts per page in pagination.

[permalinks]
    post = "/blog/:year/:month/:day/:slug/"

############################################
# Main Menu
############################################
# Important! No two menu items can have the same name (even two submenu items from two different menus)
###########################################

# Design Library
#################
[[menu.library]]

# DeclareDesign
#################
[[menu.declaredesign]]
  name = "Using DeclareDesign"
  weight = 1
  [[menu.declaredesign]]
    parent = "Using DeclareDesign"
    name = "Custom Functions"
    url = "/r/declaredesign/articles/custom_functions.html"
    weight = 1
[[menu.declaredesign]]
  name = "Reference"
  url = "/r/declaredesign/reference/"
  weight = 3

# randomizr for R
#################
[[menu.randomizr]]
  name = "Getting Started"
  url = "/r/randomizr/articles/randomizr_vignette.html"
  weight = 1
[[menu.randomizr]]
  name = "Reference"
  url = "/r/randomizr/reference/"
  weight = 2

# randomizr for Stata
#################
[[menu.strandomizr]]
  name = "Getting Started"
  url = "/stata/randomizr/articles/strandomizr_vignette.html"
  weight = 1

# fabricatr
#################
[[menu.fabricatr]]
  identifier = "getting_started"
  name = "Getting Started"
  weight = 1
  [[menu.fabricatr]]
    parent = "getting_started"
    name = "Getting Started with fabricatr"
    url = "/r/fabricatr/articles/getting_started.html"
    weight = 1
  [[menu.fabricatr]]
    parent = "getting_started"
    name = "Building and Importing Data"
    url = "/r/fabricatr/articles/building_importing.html"
    weight = 2
  [[menu.fabricatr]]
    parent = "getting_started"
    name = "Common Social Science Variables"
    url = "/r/fabricatr/articles/common_social.html"
    weight = 3
  [[menu.fabricatr]]
    parent = "getting_started"
    name = "Generating Variables"
    url = "/r/fabricatr/articles/variable_generation.html"
    weight = 4
  [[menu.fabricatr]]
    parent = "getting_started"
    name = "Panel and Cross-Classified Data"
    url = "/r/fabricatr/articles/cross_classified.html"
    weight = 5
  [[menu.fabricatr]]
    parent = "getting_started"
    name = "Resampling"
    url = "/r/fabricatr/articles/resampling.html"
    weight = 6
  [[menu.fabricatr]]
    parent = "getting_started"
    name = "Time Series Data"
    url = "/r/fabricatr/articles/time_series.html"
    weight = 7
  [[menu.fabricatr]]
    parent = "getting_started"
    name = "Advanced Features for fabricatr"
    url = "/r/fabricatr/articles/advanced_features.html"
    weight = 8
  [[menu.fabricatr]]
    parent = "getting_started"
    name = "Other Packages"
    url = "/r/fabricatr/articles/other_packages.html"
    weight = 9
[[menu.fabricatr]]
  name = "Reference"
  url = "/r/fabricatr/reference/"
  weight = 2

# estimatr
#################
[[menu.estimatr]]
  identifier = "getting_started"
  name = "Getting Started"
  weight = 1
  [[menu.estimatr]]
    parent = "getting_started"
    name = "Getting Started with estimatr"
    url = "/r/estimatr/articles/getting-started.html"
    weight = 1
  [[menu.estimatr]]
    parent = "getting_started"
    name = "Regression Tables with estimatr"
    url = "/r/estimatr/articles/regression-tables.html"
    weight = 2
  [[menu.estimatr]]
    parent = "getting_started"
    name = "Absorbing Fixed Effects with estimatr"
    url = "/r/estimatr/articles/absorbing-fixed-effects.html"
  weight = 3
  [[menu.estimatr]]
    parent = "getting_started"
    name = "estimatr in the Tidyverse"
    url = "/r/estimatr/articles/estimatr-in-the-tidyverse.html"
    weight = 4
[[menu.estimatr]]
  identifier = "technical_notes"
  name = "Technical Notes"
  weight = 2
  [[menu.estimatr]]
    parent = "technical_notes"
    name = "Mathematical Notes"
    url = "/r/estimatr/articles/mathematical-notes.html"
    weight = 1
  [[menu.estimatr]]
    parent = "technical_notes"
    name = "Simulations - Speed Comparisons"
    url = "/r/estimatr/articles/benchmarking-estimatr.html"
    weight = 2
  [[menu.estimatr]]
    parent = "technical_notes"
    name = "Simulations - OLS and Variance"
    url = "/r/estimatr/articles/simulations-ols-variance.html"
    weight = 3
  [[menu.estimatr]]
    parent = "technical_notes"
    name = "Simulations - Debiasing Difference-in-Means"
    url = "/r/estimatr/articles/simulations-debiasing-dim.html"
    weight = 4
  [[menu.estimatr]]
    parent = "technical_notes"
    name = "How Stata's hat matrix differs with weights"
    url = "/r/estimatr/articles/stata-wls-hat.html"
    weight = 5
[[menu.estimatr]]
  name = "Reference"
  url = "/r/estimatr/reference/"
  weight = 3

[params]
    description = "Declare and diagnose research designs to understand and improve them"

    # Options for highlight.js
    highlightjsVersion = "9.13.1"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    # Options for MathJax
    MathJaxVersion = "2.7.5"

  # Save this for later.
  #  [params.logo]
  #  url = "logo.png"
  #  width = 222
  #  height = 476
  #  alt = "Logo"
