---
title: "Home Page"
---
# Declaring and Diagnosing Research Designs

Empirical social scientists routinely face two research design problems. First, we need to select
a high-quality design, given resource constraints. Second, we need to convince readers and
reviewers of the design’s high quality. 

We describe in this Web site an approach to *declaring* the elements of a research design in 
code and *diagnosing* the properties of the design, such as power and sampling bias, given 
assumptions. See [The Idea](/idea) for an outline of the approach.

Ex ante declaration and diagnosis of designs can help researchers improve their
properties. Readers can more easily evaluate a research strategy prior to implementation
and without access to results. Ex post, declaration and diagnosing can also make it easier for 
designs to be shared, improved, and critiqued.

# Design Library

To make getting started easy, we provide a library of common research designs that you can use, 
diagnose, and modify. The [Design Library](/library) includes written descriptions of designs
and the code used to declare and diagnose them.

# Software

We provide four linked software packages to declare and diagnose research designs.

1. [randomizr](/R/randomizr): Easy-to-use tools for common forms of random assignment and sampling.
2. [fabricatr](/R/fabricatr): Imagine your data before you collect it.
3. [estimatr](/R/estimatr): Fast estimators for design-based inference.
4. [DeclareDesign](/R/DeclareDesign): Declare and diagnose research designs.

The [Getting Started](/R/DeclareDesign) guide for DeclareDesign provides an overview of
the capabilities of each package and how to declare and diagnose designs in our framework.

# Getting help

We provide documentation and getting started guides for each package. If you get stuck, we 
encourage you to head over to our [help forum](http://discuss.declaredesign.org) where
we'll be happy to assist with our software or coding your design.

# Contributing

There are several ways to contribute to this project. We especially encourage you to 
contribute your own research design to our design library. You can submit bug reports and feature
requests through each software package's Github repository. We ask that you agree to our 
[code of conduct](/conduct) when you contribute.

